### YamlMime:ManagedReference
items:
- uid: "com.azure.data.appconfiguration"
  id: "appconfiguration"
  children:
  - "com.azure.data.appconfiguration.AzureConfiguration"
  - "com.azure.data.appconfiguration.ConfigurationAsyncClient"
  - "com.azure.data.appconfiguration.ConfigurationClient"
  - "com.azure.data.appconfiguration.ConfigurationClientBuilder"
  - "com.azure.data.appconfiguration.ConfigurationClientCredentials"
  - "com.azure.data.appconfiguration.ConfigurationClientCredentials.AuthorizationHeaderProvider"
  - "com.azure.data.appconfiguration.ConfigurationClientCredentials.CredentialInformation"
  - "com.azure.data.appconfiguration.ConfigurationCredentialsPolicy"
  - "com.azure.data.appconfiguration.ConfigurationService"
  langs:
  - "java"
  name: "com.azure.data.appconfiguration"
  nameWithType: "com.azure.data.appconfiguration"
  fullName: "com.azure.data.appconfiguration"
  type: "Namespace"
  summary: "Package containing classes for creating a <xref uid=\"com.azure.data.appconfiguration.ConfigurationAsyncClient\" data-throw-if-not-resolved=\"false\">com.azure.data.appconfiguration.ConfigurationAsyncClient</xref> to\n perform operations on Azure App Configuration service."
  syntax:
    content: "package com.azure.data.appconfiguration"
references:
- uid: "com.azure.data.appconfiguration.AzureConfiguration"
  name: "AzureConfiguration"
  nameWithType: "AzureConfiguration"
  fullName: "com.azure.data.appconfiguration.AzureConfiguration"
- uid: "com.azure.data.appconfiguration.ConfigurationAsyncClient"
  name: "ConfigurationAsyncClient"
  nameWithType: "ConfigurationAsyncClient"
  fullName: "com.azure.data.appconfiguration.ConfigurationAsyncClient"
- uid: "com.azure.data.appconfiguration.ConfigurationClient"
  name: "ConfigurationClient"
  nameWithType: "ConfigurationClient"
  fullName: "com.azure.data.appconfiguration.ConfigurationClient"
- uid: "com.azure.data.appconfiguration.ConfigurationClientBuilder"
  name: "ConfigurationClientBuilder"
  nameWithType: "ConfigurationClientBuilder"
  fullName: "com.azure.data.appconfiguration.ConfigurationClientBuilder"
- uid: "com.azure.data.appconfiguration.ConfigurationClientCredentials"
  name: "ConfigurationClientCredentials"
  nameWithType: "ConfigurationClientCredentials"
  fullName: "com.azure.data.appconfiguration.ConfigurationClientCredentials"
- uid: "com.azure.data.appconfiguration.ConfigurationClientCredentials.AuthorizationHeaderProvider"
  name: "ConfigurationClientCredentials.AuthorizationHeaderProvider"
  nameWithType: "ConfigurationClientCredentials.AuthorizationHeaderProvider"
  fullName: "com.azure.data.appconfiguration.ConfigurationClientCredentials.AuthorizationHeaderProvider"
- uid: "com.azure.data.appconfiguration.ConfigurationClientCredentials.CredentialInformation"
  name: "ConfigurationClientCredentials.CredentialInformation"
  nameWithType: "ConfigurationClientCredentials.CredentialInformation"
  fullName: "com.azure.data.appconfiguration.ConfigurationClientCredentials.CredentialInformation"
- uid: "com.azure.data.appconfiguration.ConfigurationCredentialsPolicy"
  name: "ConfigurationCredentialsPolicy"
  nameWithType: "ConfigurationCredentialsPolicy"
  fullName: "com.azure.data.appconfiguration.ConfigurationCredentialsPolicy"
- uid: "com.azure.data.appconfiguration.ConfigurationService"
  name: "ConfigurationService"
  nameWithType: "ConfigurationService"
  fullName: "com.azure.data.appconfiguration.ConfigurationService"
