### YamlMime:ManagedReference
items:
- uid: "com.azure.data.appconfiguration.implementation"
  id: "implementation"
  children:
  - "com.azure.data.appconfiguration.implementation.ConfigurationSettingPage"
  langs:
  - "java"
  name: "com.azure.data.appconfiguration.implementation"
  nameWithType: "com.azure.data.appconfiguration.implementation"
  fullName: "com.azure.data.appconfiguration.implementation"
  type: "Namespace"
  summary: "Package containing implementation classes for communicating with Azure App Configuration service.\n Should not be used."
  syntax:
    content: "package com.azure.data.appconfiguration.implementation"
references:
- uid: "com.azure.data.appconfiguration.implementation.ConfigurationSettingPage"
  name: "ConfigurationSettingPage"
  nameWithType: "ConfigurationSettingPage"
  fullName: "com.azure.data.appconfiguration.implementation.ConfigurationSettingPage"
